name: docker-deploy.yml
on:
  push:
    branches:
      - development
      - master

jobs:
  pre-build:
    runs-on:
      - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

  build-docker:
    needs: pre-build
    runs-on:
      - self-hosted
    environment: ${{ github.base_ref == 'main' && 'PRD' || 'DEV' }}

    steps:
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ vars.DOCKERHUB_LOGIN }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_LOGIN }}/${{ vars.DOCKER_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BUILD_COMMAND="npm run ${{ vars.BUILD_COMMAND }}"

      - name: Deploy container locally
        run: |
          docker stop ${{ vars.DOCKER_NAME }} || true
          docker rm ${{ vars.DOCKER_NAME }} || true
          docker pull ${{ vars.DOCKERHUB_LOGIN }}/${{ vars.DOCKER_NAME }}:${{ github.ref_name }}
          docker run -d \
            --name ${{ vars.DOCKER_NAME }} \
            --network ${{ vars.DOCKER_NETWORK }} \
            -p 4000:80 \
            ${{ vars.DOCKERHUB_LOGIN }}/${{ vars.DOCKER_NAME }}:${{ github.ref_name }}
